### ISSUE TITLE
Recommended way to store context and targets

### ISSUE THREAD

**Issue by SeleDreams** [rust3ds/citro3d-rs#13]
Hi,
I'm new to rust as I'm more used to C and C++, I've been trying to work on a rust engine supporting 3ds however i'm having some issues.
Basically I want to have a struct that contains the data related to graphics of the engine. So the context etc
I originally approached it by trying to reproduce the triangle example but putting the data in a struct etc instead of putting everything in main
![image](https://user-images.githubusercontent.com/16335601/217389291-a4a1f390-65e1-4929-942c-5c4c57605b04.png)

however when constructing the struct I realise that due to the self references, i can't make an appropriate constructor
so I'm wondering what's the recommended approach when working with citro3d-rs

**Comment by SeleDreams** [comment]
like, I can do a struct like this
![Capture d’écran du 2023-02-08 00-34-54](https://user-images.githubusercontent.com/16335601/217391178-34980455-ab02-4fcf-8fff-5f5dd5eb5595.png)

but i'm not too sure about the best way to then have the render targets defined in the struct

**Comment by SeleDreams** [comment]
after talking on the rust discord about it, it seems like it is an actual software design incompatibility with the way the API is currently handled. 
maybe Rc or Arc could be used for some of these functions

**Comment by AzureMarker** [comment]
By holding everything in one struct you cause it to become self-referential. That means it holds references to other parts of itself. If the struct gets moved somewhere else, those references (pointers) are now invalid, causing memory issues.

We use `RefMut` internally to make sure things like the top screen aren't written to by two things at once. That has a lifetime, causing your issue.

You probably don't need ownership of `Gfx`, which is what the `RefMut` references are referring to, so you can try holding a reference to it instead.

**Comment by SeleDreams** [comment]
> By holding everything in one struct you cause it to become self-referential. That means it holds references to other parts of itself. If the struct gets moved somewhere else, those references (pointers) are now invalid, causing memory issues.
> 
> We use `RefMut` internally to make sure things like the top screen aren't written to by two things at once. That has a lifetime, causing your issue.
> 
> You probably don't need ownership of `Gfx`, which is what the `RefMut` references are referring to, so you can try holding a reference to it instead.

Thanks for the advice, i ended up making main send a Gfx reference to my struct constructor, that seems to have done the trick

**Comment by ian-h-chamberlain** [comment]
@SeleDreams just so you know, this library is in very early stages (even compared to `ctru-rs` which is also still under development), so some of these APIs are likely to change in the near future. In particular, lifetimes for this stuff get tricky since a lot of the time we are using `citro3d` C structs under the hood, so there is usually some experimentation needed to figure out the best way to represent those things (for example, #4 is somewhat related).

That said, the `Gfx` itself is not likely to change, and having a global instance with references to it like that will probably remain the best way to use it like you have done now. So I think I'll go ahead and close this issue.
