### ISSUE TITLE
Missing Bindings: citro3d/tex3ds.h

### ISSUE THREAD

**Issue by hYdos** [rust3ds/citro3d-rs#6]
Without these bindings, It is currently impossible to use textures within a rust environment

EDIT: this may technically come under another repo, But its a essential feature

**Comment by ian-h-chamberlain** [comment]
Ah, this is probably just an oversight from the early days of this repo since `citro3d.h` does not automatically include `tex3ds.h` (but does automatically include pretty much everything else in `c3d/`).

There are a few options that would probably resolve it easily:
* Create a `bindings.h` or something that includes both `citro3d.h` and `tex3ds.h`, and run bindgen on that
* Explicitly run bindgen against just `tex3ds.h` and put the output in a `mod tex3ds` or something
* Actually just run bindgen on `tex3ds.h` itself, since it apparently includes `citro3d.h` already

I don't think it makes sense to split out to a separate repo since there are just a handful of types and functions in there. Some of them look to be `static inline` and so probably will need to be ported by hand as well for full parity with the C header.

**Comment by ian-h-chamberlain** [comment]
This should be completely resolved as of #26 since bindings are now generated on the fly, including `static inline` functions and `tex3ds.h`.
